title: "Karl Belanger Portfolio"
description: "Linux Administration Projects, Accessibility Insights, and Homelab Engineering"
remote_theme: pages-themes/cayman@v0.2.0

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme

# Navigation
include:
  - index.md
  - projects.md
  - my-linux-accessibility-journey.md

# Author info
author:
  name: "Karl Belanger"
  linkedin: "https://www.linkedin.com/in/karl-belanger-09761b21/"

# Defaults for all Markdown pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
